const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('dist/index.html','utf8'),core=html.match(/<script id="poker-core">([\s\S]*?)<\/script>/)[1],ctx=vm.createContext({});vm.runInContext(core+'\nglobalThis.P=Poker;',ctx);
const E=require('../src/solver.js')(ctx.P),P=ctx.P;let passed=0;const test=(name,fn)=>{fn();passed++;console.log('OK '+name)};
const cards=s=>s.split(' ').map(c=>'23456789TJQKA'.indexOf(c[0])*4+'cdhs'.indexOf(c[1]));
const cfg=(n=3,stacks)=>({players:n,hero:n===3?'BTN':'SB',stacks:stacks||(n===3?{BTN:10,SB:10,BB:10}:{SB:10,BB:10}),sb:.5,ante:0,anteMode:'each',objective:'chipEV',payouts:n===3?[1,0,0]:[1,0],rake:0});
const opts=(n=3,extra={})=>({config:cfg(n),model:'extended',openSize:2,iterations:3000,evaluationDeals:2000,seed:783,...extra});
test('7-card category ordering, wheel, flush, full houses and kickers',()=>{const values=['Ac Kd 9h 7c 5s 3c 2d','Ac Ad 9h 7c 5s 3c 2d','Ac Ad 9h 9c 5s 3c 2d','Ac Ad Ah 9c 5s 3c 2d','Ac 2d 3h 4c 5s 9c Td','Ac Kc 9c 7c 5c 3s 2d','Ac Ad Ah 9c 9s 3c 2d','Ac Ad Ah As 9s 3c 2d','Ac 2c 3c 4c 5c 9s Td'].map(s=>E.evaluate7(cards(s)));for(let i=1;i<values.length;i++)assert.ok(values[i]>values[i-1]);assert.equal(values[4],E.score(4,[5]));assert.equal(values[8],E.score(8,[5]));assert.equal(E.evaluate7(cards('Ac Ad Ah Kc Kd Kh 2s')),E.score(6,[14,13]));assert.equal(E.evaluate7(cards('Ac Ad Kc Kd Qh Qc Js')),E.score(2,[14,13,12]))});
// Independent 5-card evaluator used across all 21 subsets of each 7-card hand.
function five(cs){const rs=cs.map(c=>(c>>2)+2).sort((a,b)=>b-a),counts=new Map();rs.forEach(r=>counts.set(r,(counts.get(r)||0)+1));const groups=[...counts].sort((a,b)=>b[1]-a[1]||b[0]-a[0]),unique=[...counts.keys()].sort((a,b)=>b-a);let st=unique.length===5&&(unique[0]-unique[4]===4)?unique[0]:unique.join(',')==='14,5,4,3,2'?5:0,flush=cs.every(c=>(c&3)===(cs[0]&3));let cat=0,ks=rs;if(flush&&st){cat=8;ks=[st]}else if(groups[0][1]===4){cat=7;ks=groups.map(g=>g[0])}else if(groups[0][1]===3&&groups[1][1]===2){cat=6;ks=groups.map(g=>g[0])}else if(flush)cat=5;else if(st){cat=4;ks=[st]}else if(groups[0][1]===3){cat=3;ks=groups.map(g=>g[0])}else if(groups[0][1]===2&&groups[1][1]===2){cat=2;ks=groups.map(g=>g[0])}else if(groups[0][1]===2){cat=1;ks=groups.map(g=>g[0])}return E.score(cat,ks)}
test('fast evaluator agrees with independent five-card enumeration on 3000 deals',()=>{const r=E.rng(771);for(let i=0;i<3000;i++){const d=E.deal(3,r),cs=[...d.holes[0],...d.board];let best=0;for(let a=0;a<7;a++)for(let b=a+1;b<7;b++)best=Math.max(best,five(cs.filter((_,k)=>k!==a&&k!==b)));assert.equal(E.evaluate7(cs),best)}});
test('deal has no duplicated cards and card classes match all 1326 combos',()=>{const counts=new Array(169).fill(0);for(let a=0;a<52;a++)for(let b=a+1;b<52;b++)counts[E.handIndex(a,b)]++;P.allHands().forEach((h,i)=>assert.equal(counts[i],h.length===2?6:h.endsWith('s')?4:12));const r=E.rng(44);for(let i=0;i<1000;i++){const d=E.deal(3,r);assert.equal(new Set([...d.holes.flat(),...d.board]).size,11)}});
test('side pots and uncalled excess settle correctly with a short-stack winner',()=>{let c=cfg(3,{BTN:20,SB:10,BB:5}),s=P.replay(c,[{player:'BTN',type:'allin',to:20},{player:'SB',type:'allin',to:10},{player:'BB',type:'allin',to:5}]),t=E.poolsFor(s);assert.deepEqual([...E.payoff(t,[1,2,3])],[-10,0,10]);assert.deepEqual([...E.payoff(t,[1,3,3])],[-10,7.5,2.5])});
test('a fold cannot win a pot even with the strongest cards',()=>{const s=P.replay(cfg(2),[{player:'SB',type:'fold'}]);assert.deepEqual([...E.payoff(E.poolsFor(s),[999999,1])],[-.5,.5])});
test('tree covers minraise, limp, flat call, 3bet and all-in paths',()=>{const g=E.build(opts());assert.ok(g.decisions.some(n=>n.history[0]?.type==='raise'&&n.position==='SB'));assert.ok(g.decisions.some(n=>n.history.filter(a=>a.type==='limp').length===2));assert.ok(g.decisions.some(n=>n.history.some(a=>a.type==='raise')&&n.actions.some(a=>a.type==='call')));assert.ok(g.decisions.some(n=>n.history.filter(a=>a.type==='raise').length===2));assert.ok(g.decisions.every(n=>n.actions.length));for(const n of g.decisions)for(const a of n.actions)assert.doesNotThrow(()=>P.apply(n.state,a))});
test('push/fold mode contains no non-all-in raises or open limps',()=>{const g=E.build(opts(3,{model:'pushfold'}));assert.ok(g.decisions.every(n=>n.actions.every(a=>!['raise','limp'].includes(a.type))))});
test('unsupported antes, model, objectives, stacks and iteration counts rejected',()=>{for(const extra of [{config:{...cfg(),ante:.1}},{config:{...cfg(),objective:'payoutEV'}},{config:cfg(3,{BTN:30,SB:10,BB:10})},{iterations:0},{model:'full-gto'}])assert.throws(()=>E.build(opts(3,extra)))});
test('policies depend on own hole category and public node, not the current board',()=>{const g=E.build(opts()),node=g.nodes[0];node.regrets[0]=3;node.regrets[1]=1;assert.equal(E.strategy(node,0,'train')[0],.75);assert.equal(E.strategy(node,0,'train')[1],.25);assert.equal(E.strategy(node,1,'train')[0],1/node.actions.length)});
test('counterfactual regret uses both opponents reach, average strategy own reach',()=>{const g=E.build(opts(3,{iterations:1})),d=E.deal(3,E.rng(55)),root=g.nodes[0],h=d.indices[0],k=root.actions.length;E.walk(g,0,d,.5,.25,.4,'train',true);for(let i=0;i<k;i++)assert.ok(Math.abs(root.regrets[h*k+i]-.1*(root.childValues[i]-root.u[0]))<1e-9);assert.ok(Math.abs(root.ownW[h]-.5)<1e-12);assert.ok(Math.abs(root.sums.slice(h*k,(h+1)*k).reduce((a,b)=>a+b,0)-.5)<1e-12)});
test('terminal payoffs conserve chips across all leaves of an asymmetric 3-player game',()=>{const g=E.build(opts(3,{config:cfg(3,{BTN:17,SB:7,BB:13})}));for(const n of g.nodes)if(n.terminal)for(const scores of [[1,2,3],[3,2,1],[3,3,3],[1,3,3]])assert.ok(Math.abs([...E.payoff(n.terminal,scores)].reduce((a,b)=>a+b,0))<1e-8)});
(async()=>{
 const run=raw=>E.run(raw,()=>{},async()=>{});
 const solved=await run(opts(2,{config:cfg(2,{SB:1,BB:1}),model:'pushfold',iterations:20000,evaluationDeals:20000}));
 test('analytical 1 BB HU game learns to shove AA against an already all-in BB',()=>{const aa=solved.nodes[0].hands.AA;assert.ok(aa.actions.find(a=>a.type==='allin').frequency>.98);assert.equal(aa.actions.find(a=>a.type==='fold').ev,-.5);assert.ok(aa.actions.find(a=>a.type==='allin').ev>.5)});
 const r=await run(opts(3));
 test('completed solver produces normalized finite mixed strategies for every tree node',()=>{assert.equal(r.trained,3000);assert.equal(r.evaluated,2000);assert.equal(r.nodes.length,r.decisionNodes);assert.ok(r.nodes.every(n=>Object.keys(n.hands).length>0));for(const node of r.nodes)for(const h of Object.values(node.hands)){assert.ok(Math.abs(h.actions.reduce((s,a)=>s+a.frequency,0)-1)<1e-8);assert.ok(h.actions.every(a=>Number.isFinite(a.frequency)&&a.frequency>=0&&a.frequency<=1));assert.ok(h.actions.every(a=>a.ev===undefined||Number.isFinite(a.ev)&&a.ci95>=0));if(h.evaluationEss<30)assert.ok(h.actions.every(a=>a.ev===undefined))}});
 const r2=await run(opts(3));
 test('same seed and parameters reproduce strategies exactly',()=>{assert.equal(JSON.stringify(r.nodes),JSON.stringify(r2.nodes))});
 console.log(passed+' solver tests passed.');
})().catch(e=>{console.error(e);process.exitCode=1});
