/* UI: standalone browser controller. Swap RangeData for a solver adapter later. */
const $=id=>document.getElementById(id), esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:3}).format(n), pct=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2,style:'percent'}).format(n);
const colors={fold:'#e6e8eb',check:'#087e83',call:'#2878b6',limp:'#b85116',raise:'#237b49',allin:'#6050a4'}, labels={fold:'Fold',check:'Check',call:'Call',limp:'Limp',raise:'Raise',allin:'All-in'};
let cfg={players:3,hero:'BTN',stacks:{BTN:25,SB:25,BB:25},sb:.5,ante:0,anteMode:'each',objective:'chipEV',payouts:[1,0,0],rake:0};
let history=[],selectedHand='AKo',handValid=true,configValid=true,packs=[],activePack=-1,mode='analyze',quiz=null,quizScore={answered:0,supported:0},cards=[null,null],cardSlot=0,toastTimer;
const pos=(p,n=cfg.players)=>n===2&&p==='SB'?'BTN / SB':p;
const pack=()=>packs[activePack]||null;
const state=()=>Poker.replay(cfg,history);
const actionName=(a,s)=>a.type==='raise'?(s.raises===0?'Raise':s.raises===1?'3-bet':(s.raises+2)+'-bet'):labels[a.type];
function actionText(a,s){let v=actionName(a,s);if(a.to!==undefined)v+=' à '+fmt(a.to)+' BB';if(a.type==='allin'&&a.to<=s.bet+Poker.EPS)v+=' (call)';return v}
function toast(m){$('toast').textContent=m;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5200)}
function error(id,m){$(id).textContent=m||'';$(id).hidden=!m}
function clearQuiz(){if(quiz){quiz=null;toast('Situation modifiée : tirez une nouvelle question.')}}
function syncForm(){
  $('hero').innerHTML=Poker.positions(cfg.players).map(p=>'<option value="'+p+'">'+pos(p)+'</option>').join('');$('hero').value=cfg.hero;
  $('stacks').innerHTML=Poker.positions(cfg.players).map(p=>'<label class="row between" style="flex-wrap:nowrap">'+pos(p)+(p===cfg.hero?' · vous':'')+'<input style="width:135px" data-stack="'+p+'" aria-label="Tapis '+pos(p)+' en BB" type="number" min="0.001" max="10000" step="0.001" value="'+cfg.stacks[p]+'"></label>').join('');
  ['sb','ante','anteMode','objective','rake'].forEach(k=>$(k).value=cfg[k]);$('payouts').value=cfg.payouts.join(', ');
  for(let n of [2,3]){$('format'+n).classList.toggle('active',cfg.players===n);$('format'+n).setAttribute('aria-pressed',cfg.players===n)}
  $('stacks').querySelectorAll('input').forEach(el=>el.addEventListener('change',readConfig));
  configValid=true;error('configError','');
}
function shiftDepth(delta,seat=null){
  if(!configValid||!Number.isFinite(delta)||delta===0)return;
  const positions=seat?[seat]:Poker.positions(cfg.players);
  if(positions.some(p=>!Object.hasOwn(cfg.stacks,p)))return;
  const values=positions.map(p=>cfg.stacks[p]);
  // Clamp the shared shift, rather than individual stacks, to preserve their gaps.
  const shift=Math.max(.001-Math.min(...values),Math.min(10000-Math.max(...values),delta));
  if(Poker.near(shift,0))return;
  const focused=document.activeElement?.dataset?.stack;
  positions.forEach(p=>document.querySelector('[data-stack="'+p+'"]').value=Poker.round(cfg.stacks[p]+shift));
  readConfig();
  if(focused)document.querySelector('[data-stack="'+focused+'"]').focus({preventScroll:true});
}
function depthWheel(event,seat=null){
  // Leave browser zoom and horizontal gestures alone; suppress native number stepping.
  if(event.ctrlKey||event.metaKey||!Number.isFinite(event.deltaY)||!event.deltaY||Math.abs(event.deltaX||0)>Math.abs(event.deltaY))return;
  event.preventDefault();
  shiftDepth(event.deltaY<0?1:-1,seat);
}
function readConfig(){try{let next={...cfg,stacks:{}};for(const p of Poker.positions(cfg.players)){const v=document.querySelector('[data-stack="'+p+'"]');next.stacks[p]=v.value.trim()===''?NaN:Number(v.value)}['sb','ante','rake'].forEach(k=>next[k]=$(k).value.trim()===''?NaN:Number($(k).value));next.hero=$('hero').value;next.anteMode=$('anteMode').value;next.objective=$('objective').value;next.payouts=$('payouts').value.split(/[,;]/).map(x=>x.trim()===''?NaN:Number(x));let valid=Poker.config(next);let sameState=JSON.stringify({...valid,hero:cfg.hero})===JSON.stringify(cfg);const had=history.length;if(!sameState)history=[];cfg=valid;configValid=true;error('configError','');clearQuiz();syncForm();if(had&&!sameState)toast('Paramètres modifiés : historique remis à zéro.');render()}catch(e){configValid=false;error('configError',e.message);render()}}
function setFormat(n){if(cfg.players===n&&configValid)return;clearQuiz();cfg={...cfg,players:n,hero:n===2?'SB':'BTN',stacks:n===2?{SB:25,BB:25}:{BTN:25,SB:25,BB:25},payouts:n===2?[1,0]:[1,0,0]};history=[];syncForm();render()}
function setHand(v,fromCards=false){try{selectedHand=Poker.hand(v);handValid=true;error('handError','');$('hand').value=selectedHand;if(!fromCards)cards=[null,null];clearQuiz();render()}catch(e){handValid=false;error('handError',e.message);render()}}
function sourceHTML(p){if(!p)return '';let r=esc(p.reference);try{let u=new URL(p.reference);if(['http:','https:'].includes(u.protocol))r='<a href="'+esc(u.href)+'" target="_blank" rel="noopener noreferrer">'+esc(p.reference)+'</a>'}catch{}return '<strong>'+esc(p.title)+'</strong><br>'+r+'<details class="gap-top"><summary>Hypothèses & provenance</summary><p>'+esc(RangeData.kinds[p.kind])+'. Source déclarée par l’auteur du fichier, non auditée.</p><p>'+esc(p.assumptions)+'</p><p><b>Postflop :</b> '+esc(p.postflop)+'</p></details>'}
function render(){
 if(mode==='solver'){renderSolver();return}
 $('solverView').hidden=true;$('navSolver').classList.toggle('active',false);$('navSolver').setAttribute('aria-pressed',false);
 if(mode==='practice'){renderPractice();return}
 $('practiceView').hidden=true;
 if(mode==='reference'){renderReference();return}
 $('referenceView').hidden=true;$('dataBanner').hidden=false;$('navReference').classList.toggle('active',false);$('navReference').setAttribute('aria-pressed',false);
 const s=state(),o=Poker.options(s),p=pack();let match=configValid?RangeData.match(p,cfg,history):null,hiddenQuiz=mode==='quiz'&&quiz&&!quiz.revealed;
 const depthValues=Object.values(cfg.stacks),sameDepth=depthValues.every(n=>Poker.near(n,depthValues[0]));
 $('depthReadout').textContent=sameDepth?fmt(depthValues[0])+' BB · tous':fmt(Math.min(...depthValues))+'–'+fmt(Math.max(...depthValues))+' BB';
 $('depthLess').disabled=!configValid||Math.min(...depthValues)<=.001; $('depthMore').disabled=!configValid||Math.max(...depthValues)>=10000;
 $('workspace').hidden=mode==='library';$('library').hidden=mode!=='library';$('quizBar').hidden=mode!=='quiz';
 for(const [id,m] of [['navAnalyze','analyze'],['navQuiz','quiz'],['navLibrary','library']]){$(id).classList.toggle('active',mode===m);$(id).setAttribute('aria-pressed',mode===m)}
 $('dataBanner').className='banner '+(!p?'info':p.provenance.kind==='demo'||p.provenance.kind==='heuristic'?'':'info');
 $('dataBanner').innerHTML=!p?'Aucune range chargée. <button class="small" id="bannerImport">Importer des ranges</button> <button class="small plain" id="bannerDemo">Essayer la démo fictive</button>':(p.provenance.kind==='demo'?'<b>DÉMO FICTIVE — aucune valeur stratégique.</b> ':p.provenance.kind==='heuristic'?'<b>Approximation pédagogique — pas une solution GTO.</b> ':'<b>Source déclarée, non auditée.</b> ')+esc(p.name)+' · '+p.spots.length+' situation(s).';
 if($('bannerImport'))$('bannerImport').onclick=()=>setMode('library');if($('bannerDemo'))$('bannerDemo').onclick=loadDemo;
 $('table').className='tablebox gap-top'+(cfg.players===2?' hu':'');$('table').innerHTML=s.ps.map(p=>{let v=s.seats[p];return '<div class="seat '+(p===cfg.hero?'hero ':'')+(v.folded?'folded':'')+'"><div>'+pos(p)+(p===cfg.hero?' · VOUS':'')+'</div><strong>'+fmt(Poker.remaining(s,p))+' <span style="font-size:12px;font-weight:400">BB</span></strong><small>'+ (v.folded?'Fold':Poker.remaining(s,p)<=Poker.EPS?'All-in':p===o?.p?'À parler':'En jeu')+'</small><small>Engagé '+fmt(v.paid)+' · ante '+fmt(v.ante)+'</small></div>'}).join('');
 $('pot').textContent='Pot brut : '+fmt(s.ps.reduce((sum,p)=>sum+s.seats[p].paid+s.seats[p].ante,0))+' BB · avant restitution des mises non suivies';
 $('effective').innerHTML=s.ps.filter(p=>p!==cfg.hero).map(p=>'<span class="metric">vs '+pos(p)+' : <b>'+fmt(Math.min(cfg.stacks[cfg.hero],cfg.stacks[p]))+' BB</b> au départ'+(s.seats[p].folded?' · fold':' · '+fmt(Math.min(s.seats[cfg.hero].cap,s.seats[p].cap))+' hors antes · '+fmt(Math.min(Poker.remaining(s,cfg.hero),Poker.remaining(s,p)))+' derrière')+'</span>').join('');
 $('streetState').textContent=!o?'Préflop terminé':o.p===cfg.hero?'À vous de parler':'À '+pos(o.p)+' de parler';
 let hs=Poker.initial(cfg);$('history').innerHTML=history.length?history.map(a=>{let html='<li>'+pos(a.player)+' · '+esc(actionText(a,hs))+'</li>';hs=Poker.apply(hs,a);return html}).join(''):'<li class="muted">Aucune action volontaire</li>';
 $('undo').disabled=!history.length;$('resetHistory').disabled=!history.length;
 $('actor').innerHTML=!configValid?'Corrigez les paramètres pour poursuivre.':o?'<b>'+pos(o.p)+(o.p===cfg.hero?' · vous':'')+'</b> · '+(o.owed?'À ajouter pour suivre : '+fmt(o.owed)+' BB.':'Check possible.'):'Tour terminé : '+(Poker.live(s).length===1?'un seul joueur reste en jeu.':'les mises sont réglées.');
 let options=[];if(o){if(o.owed>0)options.push(['fold','Fold']);options.push([o.passive,actionText({type:o.passive,...(o.owed?{to:o.callTo}:{})},s)]);if(o.canFullRaise)options.push(['raise',actionName({type:'raise'},s)]);if(o.canJam&&!options.some(x=>x[0]==='allin'))options.push(['allin','All-in à '+fmt(o.max)+' BB'])}
 const prev=$('actionType').value;$('actionType').innerHTML=options.map(([v,l])=>'<option value="'+v+'">'+esc(l)+'</option>').join('');if(options.some(x=>x[0]===prev))$('actionType').value=prev;
 $('actionType').disabled=!o||!configValid;$('addAction').disabled=!o||!configValid;$('actionAmount').value=o?o.min:'';updateActionAmount();
 $('actionHelp').textContent=o?(o.canRaise?'Relance minimale : '+fmt(o.min)+' BB au total, hors ante. Un all-in plus petit reste possible.':!o.reopened?'Une relance all-in incomplète n’a pas rouvert votre droit de relancer.':'Aucune relance possible contre des adversaires déjà à tapis.'):'Vous pouvez annuler une action ou commencer une nouvelle situation.';
 if(o&&o.canRaise&&o.max>=o.min)$('actionHelp').textContent='Relance minimale : '+fmt(o.min)+' BB au total, hors ante. Les montants incluent la blinde déjà engagée.';
 $('handCombos').textContent=handValid?(selectedHand.length===2?'6':selectedHand.endsWith('s')?'4':'12')+' combos':'—';cards.forEach((c,i)=>$('pickCard'+(i+1)).textContent=c?c[0]+({s:'♠',h:'♥',d:'♦',c:'♣'}[c[1]]):'＋ Carte '+(i+1));
 const covered=match?Object.keys(match.hands).length:0;$('coverage').textContent=hiddenQuiz?'Fréquences masquées pendant la question':match?covered+' / 169 mains renseignées · '+match.label:!configValid?'Paramètres invalides':!o?'Tour terminé':o.p!==cfg.hero?'Complétez les actions jusqu’à votre tour':'Aucune correspondance exacte';
 $('matrix').innerHTML=Poker.allHands().map(h=>{const v=!hiddenQuiz&&match?.hands[h];let bg='',title=h+' · Non couverte';if(v){let stop=0;bg='background:linear-gradient(90deg,'+v.actions.filter(a=>a.frequency>0).map(a=>{let start=stop;stop+=a.frequency*100;return colors[a.type]+' '+start+'% '+stop+'%'}).join(',')+')';title=h+' · '+v.actions.map(a=>actionText(a,s)+' '+pct(a.frequency)).join(' / ')}if(hiddenQuiz)title=h+' · Fréquences masquées';return '<button class="cell '+(v?'known ':'')+(v&&v.actions.every(a=>a.frequency===0||a.type==='fold')?'fold-only ':'')+(handValid&&h===selectedHand?'selected':'')+'" data-hand="'+h+'" aria-label="'+esc(title)+'" aria-pressed="'+(handValid&&h===selectedHand)+'" title="'+esc(title)+'" style="'+bg+'">'+h+'</button>'}).join('');
 $('legend').innerHTML=Object.entries(labels).map(([k,l])=>'<span><span class="swatch" style="background:'+colors[k]+'"></span>'+l+'</span>').join('')+'<span><span class="swatch unknown"></span>Non couverte</span>';
 $('quizChoices').hidden=true;$('quizFeedback').hidden=true;
 let data=handValid&&match?.hands[selectedHand];
 if(hiddenQuiz){$('result').innerHTML='<h2 class="result-title">'+esc(selectedHand)+'</h2><p class="muted">Quelle action choisissez-vous ?</p><p class="note">Une stratégie mixte peut prévoir plusieurs actions.</p>';renderQuizChoices(s,data)}
 else if(mode==='quiz'&&!quiz){$('result').innerHTML='<h2 class="result-title">À vous de jouer</h2><p class="muted">Tirez une question depuis la bibliothèque active.</p>'}
 else if(!configValid||!handValid){$('result').innerHTML='<div class="result-empty"><h2 class="result-title">Saisie à corriger</h2><p class="muted">Vérifiez les champs signalés.</p></div>'}
 else if(!o||o.p!==cfg.hero){$('result').innerHTML='<div class="result-empty"><h2 class="result-title">'+(!o?'Préflop terminé':'En attente de '+pos(o.p))+'</h2><p class="muted">'+(!o?'Revenez avant votre décision pour consulter une range.':'Ajoutez les actions précédentes jusqu’à votre tour.')+'</p></div>'}
 else if(!data){$('result').innerHTML='<div class="result-empty"><h2 class="result-title">Situation non couverte</h2><p class="muted">'+(!p?'Importez des ranges documentées ou essayez la démo fictive.':!match?'Aucune situation ne correspond exactement à ces tapis, paramètres et actions.':'Cette situation est disponible, mais la main '+esc(selectedHand)+' n’est pas renseignée.')+'</p></div><p class="note">Aucune action ni EV n’est inventée.</p>'}
 else renderRecommendation(s,data,p);
 if(mode==='quiz'&&quiz?.revealed){$('quizFeedback').hidden=false;$('quizFeedback').textContent=quiz.feedback}
 $('quizStats').textContent=quizScore.supported+' / '+quizScore.answered+' réponses prévues par les ranges · plusieurs actions peuvent être valides';$('quizReveal').disabled=!quiz||quiz.revealed;$('quizNext').disabled=!p||!p.spots.some(v=>Object.keys(v.hands).length);
 renderLibrary();
}
function renderRecommendation(s,data,p){let sorted=[...data.actions].sort((a,b)=>b.frequency-a.frequency),best=sorted[0],positive=sorted.filter(a=>a.frequency>0),demo=p.provenance.kind==='demo';let title=actionText(best,s);let amount=best.to!==undefined?'<p class="smalltext">'+fmt(best.to)+' BB au total préflop · <b>'+fmt(best.to-s.seats[cfg.hero].paid)+' BB à ajouter</b> · hors ante.</p>':'';
 $('result').innerHTML='<div class="recommendation"><span class="pill">'+(demo?'DÉMO · PAS UN CONSEIL':positive.length>1?'Stratégie mixte':'Action de la range')+'</span><h2 class="result-title">'+esc(title)+'</h2>'+amount+'<p class="note">'+(positive.length>1?'Action la plus fréquente : '+pct(best.frequency)+'. Respectez aussi les autres fréquences.':pct(best.frequency)+' dans la range importée.')+'</p></div><div class="freq">'+sorted.map(a=>'<span style="width:'+a.frequency*100+'%;background:'+colors[a.type]+'"></span>').join('')+'</div><table class="distribution"><thead><tr><th>Action · total BB</th><th>Fréq.</th>'+(data.actions.some(a=>a.ev!==undefined)?'<th>EV</th>':'')+'</tr></thead><tbody>'+sorted.map(a=>'<tr><td><span class="swatch" style="background:'+colors[a.type]+'"></span>'+esc(actionText(a,s))+'</td><td>'+pct(a.frequency)+'</td>'+(data.actions.some(a=>a.ev!==undefined)?'<td>'+(a.ev!==undefined?fmt(a.ev):'—')+'</td>':'')+'</tr>').join('')+'</tbody></table><p class="note">'+(data.actions.some(a=>a.ev!==undefined)?'EV fournie par la source · '+esc(p.provenance.evUnit):'EV non disponible : aucun calcul effectué.')+'</p><p class="smalltext gap-top">'+esc(data.explanation)+'</p><p class="note">Objectif : '+(cfg.objective==='chipEV'?'chip EV':'EV des gains selon le modèle fourni')+'.</p><div class="source">'+sourceHTML(p.provenance)+'</div>';
}
function updateActionAmount(){let s=state(),o=Poker.options(s),raise=$('actionType').value==='raise';$('actionAmount').disabled=!raise||!o||!configValid;if(o){$('actionAmount').min=o.min;$('actionAmount').max=o.max;if(!raise)$('actionAmount').value=['call','limp'].includes($('actionType').value)?o.callTo:$('actionType').value==='allin'?o.max:''}$('amountLabel').style.opacity=raise?'1':'.6'}
function setMode(m){mode=m;render()}
function addAction(){try{if(!configValid)return;let s=state(),o=Poker.options(s);if(!o)return;const a={player:o.p,type:$('actionType').value};if(a.type==='raise')a.to=Number($('actionAmount').value);const ns=Poker.apply(s,a);history=ns.history;error('actionError','');clearQuiz();render()}catch(e){error('actionError',e.message)}}
function renderLibrary(){const p=pack();$('packSelect').innerHTML=packs.length?packs.map((p,i)=>'<option value="'+i+'">'+esc(p.name)+'</option>').join(''):'<option value="-1">Aucune bibliothèque</option>';$('packSelect').value=activePack;const selected=$('spotSelect').value;$('spotSelect').innerHTML=p?p.spots.map((s,i)=>'<option value="'+i+'">'+esc(s.label)+' · '+Object.keys(s.hands).length+' mains</option>').join(''):'<option>Aucune situation</option>';if(p&&p.spots[Number(selected)])$('spotSelect').value=selected;$('packDetails').innerHTML=p?sourceHTML(p.provenance):'Importez votre fichier ou chargez la démo pour essayer.';$('loadSpot').disabled=!p;$('exportPack').disabled=!p;$('clearPacks').disabled=!packs.length;}
function openSpot(i,h){let sp=pack()?.spots[i];if(!sp)return;cfg=structuredClone(sp.config);history=structuredClone(sp.history);selectedHand=h||Object.keys(sp.hands)[0]||'AKo';handValid=true;cards=[null,null];$('hand').value=selectedHand;error('handError','');error('actionError','');syncForm()}
function acceptPack(raw){const validated=RangeData.validate(raw);packs.push(validated);activePack=packs.length-1;quiz=null;quizScore={answered:0,supported:0};return validated}
const demo=()=>({schemaVersion:1,name:'Démo fictive · 3 situations',provenance:{kind:'demo',title:'Exemples d’interface Expresso Lab',reference:'Données inventées pour démontrer le fonctionnement, version 1.0',assumptions:'Fréquences arbitraires. Aucune valeur stratégique, aucun équilibre calculé. Sans ante, blindes 0,5 / 1, rake nul. Les mains absentes ne sont pas couvertes.',postflop:'Aucun jeu postflop modélisé. Ces exemples ne sont pas des solutions préflop.'},spots:[{label:'Démo · BTN · 3 joueurs · 10 BB',config:{players:3,hero:'BTN',stacks:{BTN:10,SB:10,BB:10},sb:.5,ante:0,anteMode:'each',objective:'chipEV',payouts:[1,0,0],rake:0},history:[],hands:{AA:{actions:[{type:'raise',to:2,frequency:.7},{type:'allin',to:10,frequency:.3}],explanation:'Exemple fictif de mélange entre deux actions pour tester les fréquences.'},AKo:{actions:[{type:'raise',to:2,frequency:.4},{type:'allin',to:10,frequency:.6}],explanation:'Fréquences inventées pour la démonstration. Ne pas les utiliser comme conseil.'},'72o':{actions:[{type:'fold',frequency:1}],explanation:'Exemple fictif d’affichage d’une action unique.'}}},{label:'Démo · BB face à 2 BB · heads-up · 15 BB',config:{players:2,hero:'BB',stacks:{SB:15,BB:15},sb:.5,ante:0,anteMode:'each',objective:'chipEV',payouts:[1,0],rake:0},history:[{player:'SB',type:'raise',to:2}],hands:{AQs:{actions:[{type:'call',to:2,frequency:.5},{type:'raise',to:5,frequency:.5}],explanation:'Exemple fictif : la blinde de 1 BB est déjà engagée. Un call à 2 ajoute 1 BB.'},'77':{actions:[{type:'call',to:2,frequency:.6},{type:'allin',to:15,frequency:.4}],explanation:'Exemple fictif pour tester une correction de quiz à plusieurs actions.'}}},{label:'Démo · BB après deux limps · 20 / 12 / 15 BB',config:{players:3,hero:'BB',stacks:{BTN:20,SB:12,BB:15},sb:.5,ante:0,anteMode:'each',objective:'chipEV',payouts:[1,0,0],rake:0},history:[{player:'BTN',type:'limp',to:1},{player:'SB',type:'limp',to:1}],hands:{'99':{actions:[{type:'check',frequency:.5},{type:'raise',to:3,frequency:.5}],explanation:'Exemple fictif de check ou relance après deux limps. Tapis effectifs distincts contre BTN et SB.'},'72o':{actions:[{type:'check',frequency:1}],explanation:'Exemple fictif pour essayer le bouton Check.'}}}]});
function loadDemo(){try{let existing=packs.findIndex(p=>p.name===demo().name&&p.provenance.kind==='demo');if(existing>=0)activePack=existing;else acceptPack(demo());quiz=null;openSpot(0,'AKo');mode='analyze';render();toast('Démo fictive chargée. Aucune recommandation fiable incluse.')}catch(e){toast(e.message)}}
function download(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function template(){if(!configValid||Poker.next(state())!==cfg.hero){toast('Arrêtez une situation valide au tour de votre héros avant de créer le modèle.');return}download('modele-range-expresso.json',{schemaVersion:1,name:'Ma bibliothèque à compléter',provenance:{kind:'reference',title:'À RENSEIGNER : titre exact',reference:'À RENSEIGNER : source, version, export ou URL',assumptions:'À RENSEIGNER : arbre de mises, méthode, paramètres et référence de l’EV si fournie',postflop:'À RENSEIGNER : traitement du postflop, ou restriction explicite au push/fold'},spots:[{label:'Ma situation',config:cfg,history,hands:{}}]})}
function newQuiz(){let p=pack(),eligible=p?.spots.map((v,i)=>({v,i})).filter(x=>Object.keys(x.v.hands).length);if(!eligible?.length){toast('Importez des ranges renseignées ou essayez la démo fictive.');return}let {v,i}=eligible[Math.floor(Math.random()*eligible.length)],hands=Object.keys(v.hands),h=hands[Math.floor(Math.random()*hands.length)];openSpot(i,h);quiz={spot:i,hand:h,revealed:false,feedback:''};mode='quiz';render()}
function renderQuizChoices(s,data){if(!data)return;let o=Poker.options(s),choices=[];if(o.owed>0)choices.push({type:'fold'});choices.push({type:o.passive,...(o.owed?{to:o.callTo}:{})});if(o.canFullRaise)choices.push({type:Poker.near(o.min,o.max)?'allin':'raise',to:o.min});if(o.canJam)choices.push({type:'allin',to:o.max});data.actions.forEach(a=>choices.push({type:a.type,...(a.to!==undefined?{to:a.to}:{})}));choices=[...new Map(choices.map(a=>[Poker.actionKey(a),a])).values()];$('quizChoices').hidden=false;$('quizChoices').innerHTML=choices.map((a,i)=>'<button class="small" data-choice="'+i+'">'+esc(actionText(a,s))+'</button>').join('');$('quizChoices').querySelectorAll('button').forEach(b=>b.onclick=()=>{let a=choices[Number(b.dataset.choice)],found=data.actions.find(x=>Poker.actionKey(x)===Poker.actionKey(a)),f=found?.frequency||0;quizScore.answered++;if(f>0)quizScore.supported++;quiz.revealed=true;quiz.feedback=(f>0?'Action prévue par cette range à '+pct(f)+'.':'Cette action a une fréquence de 0 % dans la range importée.')+' Votre réponse : '+actionText(a,s)+'. '+(pack().provenance.kind==='demo'?'Exercice fictif, sans valeur stratégique.':'Ce score vérifie l’appartenance à la stratégie, pas le respect de ses fréquences à long terme.');render()})}
function chooseCard(slot){cardSlot=slot;$('cardDialogTitle').textContent='Choisir la carte '+(slot+1);$('deck').innerHTML=['s','h','d','c'].flatMap(suit=>[...'AKQJT98765432'].map(r=>{let card=r+suit;return '<button class="'+(['h','d'].includes(suit)?'red ':'')+(cards[slot]===card?'picked':'')+'" data-card="'+card+'" aria-label="'+r+' '+({s:'pique',h:'cœur',d:'carreau',c:'trèfle'}[suit])+'" '+(cards[1-slot]===card?'disabled':'')+'>'+r+({s:'♠',h:'♥',d:'♦',c:'♣'}[suit])+'</button>'})).join('');$('deck').querySelectorAll('button').forEach(b=>b.onclick=()=>{cards[slot]=b.dataset.card;$('cardDialog').close();if(cards.every(Boolean)){let [a,b]=cards;setHand(a[0]+b[0]+(a[0]===b[0]?'':a[1]===b[1]?'s':'o'),true)}else{handValid=false;error('handError','Choisissez la deuxième carte pour définir votre main.');clearQuiz();render()}});$('cardDialog').showModal()}
$('navAnalyze').onclick=()=>{quiz=null;setMode('analyze')};$('navQuiz').onclick=()=>{mode='practice';render()};$('navLibrary').onclick=()=>setMode('library');
$('stacks').addEventListener('wheel',event=>{const el=event.target.closest('input[data-stack]');if(el)depthWheel(event,el.dataset.stack)},{passive:false});
$('depthWheel').addEventListener('wheel',event=>depthWheel(event),{passive:false});
$('depthLess').onclick=()=>shiftDepth(-1);$('depthMore').onclick=()=>shiftDepth(1);
$('format3').onclick=()=>setFormat(3);$('format2').onclick=()=>setFormat(2);
['hero','sb','ante','anteMode','objective','payouts','rake'].forEach(k=>$(k).addEventListener('change',readConfig));
$('depths').innerHTML=[3,5,7,10,12,15,20,25].map(n=>'<button data-depth="'+n+'" title="Mettre tous les tapis à '+n+' BB">'+n+'</button>').join('');$('depths').querySelectorAll('button').forEach(b=>b.onclick=()=>{clearQuiz();Object.keys(cfg.stacks).forEach(p=>cfg.stacks[p]=Number(b.dataset.depth));history=[];syncForm();render()});
$('hand').addEventListener('change',()=>setHand($('hand').value));$('hand').addEventListener('keydown',e=>{if(e.key==='Enter')setHand($('hand').value)});$('matrix').addEventListener('click',e=>{let b=e.target.closest('[data-hand]');if(b)setHand(b.dataset.hand)});
$('pickCard1').onclick=()=>chooseCard(0);$('pickCard2').onclick=()=>chooseCard(1);$('closeCards').onclick=()=>$('cardDialog').close();
$('actionType').onchange=updateActionAmount;$('addAction').onclick=addAction;$('undo').onclick=()=>{history.pop();error('actionError','');clearQuiz();render()};$('resetHistory').onclick=()=>{history=[];error('actionError','');clearQuiz();render()};
$('loadDemo').onclick=loadDemo;$('importFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw new Error('Fichier trop volumineux : maximum 5 Mo.');let p=acceptPack(JSON.parse(await f.text()));$('importStatus').textContent='Import réussi : '+p.spots.length+' situation(s), source déclarée non auditée.';render();toast('Bibliothèque importée. Choisissez une situation à ouvrir.')}catch(err){$('importStatus').textContent='Import refusé : '+err.message}finally{e.target.value=''}};
$('packSelect').onchange=e=>{activePack=Number(e.target.value);quiz=null;quizScore={answered:0,supported:0};render()};$('loadSpot').onclick=()=>{quiz=null;openSpot(Number($('spotSelect').value));mode='analyze';render()};$('exportPack').onclick=()=>{if(pack())download('bibliotheque-expresso.json',pack())};$('clearPacks').onclick=()=>{packs=[];activePack=-1;quiz=null;quizScore={answered:0,supported:0};$('importStatus').textContent='Bibliothèques retirées de la mémoire.';render()};$('downloadTemplate').onclick=template;$('downloadDemo').onclick=()=>download('demo-fictive-expresso.json',demo());
$('quizNext').onclick=newQuiz;$('quizReveal').onclick=()=>{if(quiz){quiz.revealed=true;quiz.feedback='Correction révélée sans réponse : non comptabilisée dans le score.';render()}};
$('schemaExample').textContent=JSON.stringify({...demo(),name:'Exemple de structure · valeurs fictives',spots:[demo().spots[0]]},null,2);
/* PDF reader: categorical source charts, separate from quantified solver ranges. */
const PDF_CHARTS=/* @REFERENCE_CHARTS@ */;
const ReferenceRanges=(()=>{
 const scenarios={
  '3:BTN':[{id:'btn_open',label:'Personne n’a ouvert',sequence:'Vous êtes au BTN et parlez en premier.'}],
  '3:SB':[{id:'sb_btn_raise',label:'BTN raise · minraise à 2 BB',sequence:'BTN ouvre à 2 BB → vous êtes en SB. La BB doit encore parler.'},{id:'sb_btn_shove',label:'BTN all-in',sequence:'BTN fait all-in → vous êtes en SB. La BB doit encore parler.'},{id:'sb_open',label:'BTN fold · ouverture de SB',sequence:'BTN se couche → vous ouvrez en SB face à la BB.'},{id:'sb_btn_limp',label:'BTN limp',sequence:'BTN limp → vous êtes en SB. La BB doit encore parler.'}],
  '3:BB':[{id:'bb_sb_raise',label:'BTN fold, puis SB raise',sequence:'BTN se couche → SB ouvre → vous êtes en BB. Taille d’ouverture non précisée dans le tableau.'},{id:'bb_sb_shove',label:'BTN fold, puis SB all-in',sequence:'BTN se couche → SB fait all-in → vous êtes en BB.'},{id:'bb_btn_raise',label:'BTN raise, puis SB fold',sequence:'BTN ouvre → SB se couche → vous êtes en BB.'},{id:'bb_btn_shove',label:'BTN all-in, puis SB fold',sequence:'BTN fait all-in → SB se couche → vous êtes en BB.'},{id:'bb_sb_limp',label:'BTN fold, puis SB limp',sequence:'BTN se couche → SB complète → vous êtes en BB.'}],
  '2:SB':[{id:'hu_sb_open',label:'Personne n’a ouvert',sequence:'Vous êtes au BTN / SB et parlez en premier face à la BB.'}],
  '2:BB':[{id:'hu_bb_raise',label:'BTN / SB raise · minraise à 2 BB',sequence:'BTN / SB ouvre à 2 BB → vous êtes en BB.'},{id:'hu_bb_limp',label:'BTN / SB limp',sequence:'BTN / SB complète à 1 BB → vous êtes en BB.'},{id:'hu_bb_shove',label:'BTN / SB all-in',sequence:'BTN / SB fait all-in → vous êtes en BB.'}]
 };
 const pages={btn_open:{25:2,15:3,10:4},sb_btn_raise:{25:5,15:6},sb_btn_shove:{10:7},sb_open:{25:8,15:9,10:10},bb_sb_raise:{25:11,15:12},bb_sb_shove:{10:13},hu_sb_open:{15:14,12:15,8:16},hu_bb_raise:{15:17},hu_bb_limp:{12:18},hu_bb_shove:{8:19}};
 const available=id=>Object.keys(pages[id]||{}).map(Number).sort((a,b)=>b-a);
 const chart=(id,depth)=>PDF_CHARTS.find(c=>c.page===pages[id]?.[depth])||null;
 const textColor=hex=>{let rgb=hex.slice(1).match(/../g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4),lum=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];return lum>.179?'#101820':'#ffffff'};
 return {scenarios,pages,available,chart,textColor};
})();
let refState={players:3,hero:'SB',scenario:'sb_btn_raise',depth:25,hand:'AKo'};
function renderReference(){
 for(const id of ['refMatrix','refLegend','refDecision'])$(id).hidden=false;
 error('refDepthError','');error('refHandError','');
 $('referenceView').hidden=false;for(const id of ['workspace','library','quizBar','dataBanner'])$(id).hidden=true;
 for(const id of ['navReference','navAnalyze','navQuiz','navLibrary']){$(id).classList.toggle('active',id==='navReference');$(id).setAttribute('aria-pressed',id==='navReference')}
 const st=refState,ps=Poker.positions(st.players),choices=ReferenceRanges.scenarios[st.players+':'+st.hero];
 $('refFormat').value=st.players;$('refPosition').innerHTML=ps.map(p=>'<option value="'+p+'">'+pos(p,st.players)+'</option>').join('');$('refPosition').value=st.hero;
 $('refSituation').innerHTML=choices.map(c=>'<option value="'+c.id+'">'+esc(c.label)+'</option>').join('');$('refSituation').value=st.scenario;
 $('refDepth').value=st.depth;$('refHand').value=st.hand;$('refLess').disabled=st.depth<=1;$('refMore').disabled=st.depth>=10000;
 const choice=choices.find(c=>c.id===st.scenario),chart=ReferenceRanges.chart(st.scenario,st.depth),depths=ReferenceRanges.available(st.scenario),allHands=Poker.allHands();
 $('refContext').textContent=st.players===3?'3 joueurs':'Heads-up';$('refTitle').textContent=pos(st.hero,st.players)+' · '+choice.label+' · '+fmt(st.depth)+' BB';$('refSequence').textContent=choice.sequence;$('refHeroLabel').textContent=pos(st.hero,st.players);
 $('refAvailable').innerHTML=depths.length?depths.map(d=>'<button data-ref-depth="'+d+'" class="'+(d===st.depth?'active':'')+'" aria-pressed="'+(d===st.depth)+'">'+d+' BB</button>').join(''):'<span class="note">Aucun tableau dans ce PDF.</span>';
 $('trainThisRange').disabled=!chart;
 $('refPage').textContent=chart?'PDF · page '+chart.page+' / 19':'PDF · tableau absent';$('refCoverage').textContent=chart?'169 / 169 mains':'0 / 169 mains';
 $('refMissing').hidden=!!chart;$('refMissing').textContent='Situation non couverte à '+fmt(st.depth)+' BB. '+(depths.length?'Tableaux disponibles pour cette action : '+depths.join(', ')+' BB.':'Le PDF ne contient aucun tableau pour cette action.')+' Aucune autre action ni profondeur n’est substituée.';
 $('refMatrix').innerHTML=allHands.map((h,i)=>{const item=chart?.legend[chart.cells[i]],label=item?item.label:'Situation non couverte',style=item?'background:'+item.color+';--cell-text:'+ReferenceRanges.textColor(item.color):'';return '<button class="cell '+(item?'known ':'')+(h===st.hand?'selected':'')+'" data-ref-hand="'+h+'" style="'+style+'" aria-pressed="'+(h===st.hand)+'" aria-label="'+esc(h+' : '+label)+'" title="'+esc(h+' : '+label)+'">'+h+'</button>'}).join('');
 $('refLegend').innerHTML=chart?chart.legend.map((l,j)=>'<span><span class="swatch" style="background:'+l.color+'"></span>'+esc(l.label)+' <span class="muted">· '+chart.cells.filter(i=>i===j).length+'</span></span>').join(''):'';
 const item=chart?.legend[chart.cells[allHands.indexOf(st.hand)]];
 $('refDecision').innerHTML=item?'<div class="eyebrow">'+esc(st.hand)+' · '+pos(st.hero,st.players)+' · '+fmt(st.depth)+' BB</div><h2 class="result-title">'+esc(item.label)+'</h2><p class="smalltext">Catégorie attribuée à cette main dans le PDF, page '+chart.page+'.</p><p class="note">'+(/non all|nai|iso \/|reraise/i.test(item.label)?'La taille exacte de cette relance n’est pas indiquée dans ce tableau. ':'')+'Les éventuels plans après « / » sont repris tels quels. Le PDF ne fournit ni fréquences ni EV ; aucun chiffre n’est ajouté.</p>':'<h2 class="result-title">Situation non couverte</h2><p class="note">Choisissez une profondeur disponible pour cette action.</p>';
}
function refChooseContext(){
 refState.players=Number($('refFormat').value);refState.hero=$('refPosition').value;
 if(!Poker.positions(refState.players).includes(refState.hero))refState.hero='SB';
 const choices=ReferenceRanges.scenarios[refState.players+':'+refState.hero];
 if(!choices.some(c=>c.id===refState.scenario))refState.scenario=choices[0].id;
 error('refDepthError','');error('refHandError','');render();
}
function refSetDepth(value){const d=Number(value);if(!Number.isInteger(d)||d<1||d>10000){error('refDepthError','Choisissez une profondeur entière entre 1 et 10 000 BB.');for(const id of ['refMatrix','refLegend','refDecision'])$(id).hidden=true;$('refCoverage').textContent='Profondeur invalide';return}refState.depth=d;error('refDepthError','');render()}
function refNudge(delta){refSetDepth(Math.max(1,Math.min(10000,refState.depth+delta)))}
$('navReference').onclick=()=>{quiz=null;mode='reference';render()};
$('refFormat').onchange=refChooseContext;$('refPosition').onchange=refChooseContext;
$('refSituation').onchange=()=>{refState.scenario=$('refSituation').value;render()};
$('refDepth').onchange=()=>refSetDepth($('refDepth').value);$('refLess').onclick=()=>refNudge(-1);$('refMore').onclick=()=>refNudge(1);
$('refWheel').addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey||!Number.isFinite(e.deltaY)||!e.deltaY||Math.abs(e.deltaX||0)>Math.abs(e.deltaY))return;e.preventDefault();refNudge(e.deltaY<0?1:-1)},{passive:false});
$('refAvailable').addEventListener('click',e=>{const b=e.target.closest('[data-ref-depth]');if(b)refSetDepth(b.dataset.refDepth)});
$('refMatrix').addEventListener('click',e=>{const b=e.target.closest('[data-ref-hand]');if(b){refState.hand=b.dataset.refHand;error('refHandError','');render()}});
$('refHand').onchange=()=>{try{refState.hand=Poker.hand($('refHand').value);error('refHandError','');render()}catch(e){error('refHandError',e.message);$('refDecision').innerHTML='<h2 class="result-title">Main à corriger</h2><p class="note">Utilisez une notation comme AKo, AQs ou 77.</p>'}};
/* Source-backed drills; no invented strategy, EV, or confidence score. */
const Practice=(()=>{
 const version=1,storageKey='expresso-lab-practice-v1',hands=Poker.allHands();
 function immediate(label){if(/^profil/i.test(label))return null;if(/^Fold$/i.test(label))return 'Fold';if(/^Call$/i.test(label))return 'Call';if(/^(Open shove|3bet All-in|Iso All-in)$/i.test(label))return 'All-in';if(/^Minraise/i.test(label))return 'Minraise · 2 BB';if(/^3x/i.test(label))return 'Raise · 3 BB';if(/^3bet/i.test(label))return '3-bet non all-in';if(/^Limp/i.test(label))return 'Limp';if(/^Iso/i.test(label))return 'Iso non all-in';if(/^Check/i.test(label))return 'Check';return null}
 const context=page=>{for(const [id,depths] of Object.entries(ReferenceRanges.pages)){for(const [depth,p] of Object.entries(depths)){if(p!==page)continue;for(const [key,options] of Object.entries(ReferenceRanges.scenarios)){const scenario=options.find(v=>v.id===id);if(scenario){const [players,hero]=key.split(':');return {players:Number(players),hero,scenario:id,depth:Number(depth),label:scenario.label,sequence:scenario.sequence}}}}}return null};
 const bank=level=>PDF_CHARTS.flatMap(c=>hands.flatMap((hand,i)=>{const plan=c.legend[c.cells[i]].label,action=immediate(plan);return action?[{key:c.page+':'+hand+':'+level,page:c.page,hand,level,plan,answer:level==='plan'?plan:action}]:[]}));
 function choices(q){const c=PDF_CHARTS.find(c=>c.page===q.page);return [...new Set(c.legend.map(l=>immediate(l.label)?q.level==='plan'?l.label:immediate(l.label):null).filter(Boolean))]}
 const pending=r=>r.wrong>0&&r.streak<2;
 function clean(raw){if(!raw||raw.version!==version||!raw.records||typeof raw.records!=='object')return {};const allowed=new Set([...bank('action'),...bank('plan')].map(q=>q.key)),records={};for(const [key,r] of Object.entries(raw.records)){if(!allowed.has(key)||!r)continue;const nums=['attempts','correct','wrong','streak'];if(nums.some(k=>!Number.isSafeInteger(r[k])||r[k]<0)||r.attempts!==r.correct+r.wrong||r.streak>r.correct)continue;records[key]={attempts:r.attempts,correct:r.correct,wrong:r.wrong,streak:r.streak}}return records}
 function record(records,key,correct){const r=records[key]||{attempts:0,correct:0,wrong:0,streak:0};return {...records,[key]:{attempts:r.attempts+1,correct:r.correct+(correct?1:0),wrong:r.wrong+(correct?0:1),streak:correct?r.streak+1:0}}}
 function totals(records){return Object.values(records).reduce((s,r)=>({attempts:s.attempts+r.attempts,correct:s.correct+r.correct,pending:s.pending+(pending(r)?1:0)}),{attempts:0,correct:0,pending:0})}
 function pool(level,scope,records,chart){return bank(level).filter(q=>scope==='all'||scope==='current'&&q.page===chart?.page||scope==='errors'&&records[q.key]&&pending(records[q.key]))}
 function pick(pool,n=10,rng=Math.random){const items=[...pool];for(let i=items.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items.slice(0,n)}
 return {version,storageKey,immediate,context,bank,choices,pending,clean,record,totals,pool,pick};
})();
let practiceRecords={},practiceSaved=false,practiceSession=null,practiceLevel='action',practiceScope='current';
try{practiceRecords=Practice.clean(JSON.parse(localStorage.getItem(Practice.storageKey)||'null'));localStorage.setItem(Practice.storageKey,JSON.stringify({version:Practice.version,records:practiceRecords}));practiceSaved=true}catch{}
function savePractice(){try{localStorage.setItem(Practice.storageKey,JSON.stringify({version:Practice.version,records:practiceRecords}));practiceSaved=true}catch{practiceSaved=false}}
const practiceChart=()=>ReferenceRanges.chart(refState.scenario,refState.depth);
function startPractice(){const pool=Practice.pool(practiceLevel,practiceScope,practiceRecords,practiceChart());if(!pool.length){practiceSession=null;render();return}practiceSession={items:Practice.pick(pool),index:0,answers:[],revealed:false,chosen:null};mode='practice';render()}
function answerPractice(answer){const session=practiceSession;if(!session||session.revealed||session.index>=session.items.length)return;const q=session.items[session.index];if(answer!==null&&!Practice.choices(q).includes(answer))return;session.chosen=answer;session.revealed=true;session.answers.push(answer===null?null:answer===q.answer);if(answer!==null){practiceRecords=Practice.record(practiceRecords,q.key,answer===q.answer);savePractice()}render()}
function nextPractice(){const s=practiceSession;if(!s||!s.revealed)return;s.index++;s.revealed=false;s.chosen=null;render()}
function renderPractice(){
 $('practiceView').hidden=false;for(const id of ['referenceView','workspace','library','quizBar','dataBanner'])$(id).hidden=true;
 for(const id of ['navReference','navAnalyze','navQuiz','navLibrary']){$(id).classList.toggle('active',id==='navQuiz');$(id).setAttribute('aria-pressed',id==='navQuiz')}
 $('practiceLevel').value=practiceLevel;$('practiceScope').value=practiceScope;
 const chart=practiceChart(),pool=Practice.pool(practiceLevel,practiceScope,practiceRecords,chart),totals=Practice.totals(practiceRecords),s=practiceSession,finished=s&&s.index>=s.items.length;
 $('practiceStart').disabled=!pool.length;
 $('practiceScopeInfo').textContent=(practiceScope==='current'?(chart?pos(refState.hero,refState.players)+' · '+refState.depth+' BB · '+ReferenceRanges.scenarios[refState.players+':'+refState.hero].find(v=>v.id===refState.scenario).label:'Ce spot n’est pas couvert : choisissez un tableau disponible dans « Mes ranges ».'):practiceScope==='all'?'18 tableaux disponibles. Chaque exercice est tiré au hasard, sans pondération par le nombre de combinaisons.':'Les exercices encore en erreur pour le niveau choisi.')+' '+pool.length+' exercice(s) disponible(s).';
 $('practiceTotal').textContent=totals.attempts;$('practiceAccuracy').textContent=totals.attempts?pct(totals.correct/totals.attempts):'—';$('practicePending').textContent=totals.pending;
 $('practiceStorage').textContent=practiceSaved?'Progression enregistrée uniquement dans ce navigateur, sur cet appareil.':'Progression conservée pour cette session seulement : le stockage du navigateur est indisponible.';
 $('practiceReview').disabled=!Practice.pool(practiceLevel,'errors',practiceRecords,chart).length;
 const weak=Practice.bank(practiceLevel).filter(q=>practiceRecords[q.key]&&Practice.pending(practiceRecords[q.key])).sort((a,b)=>practiceRecords[b.key].wrong-practiceRecords[a.key].wrong).slice(0,6);
 $('practiceWeaknesses').innerHTML=weak.length?weak.map(q=>{const c=Practice.context(q.page),r=practiceRecords[q.key];return '<div class="practice-mistake"><strong>'+q.hand+' · '+pos(c.hero,c.players)+' · '+c.depth+' BB</strong><br><span class="muted">'+esc(c.label)+' · '+r.wrong+' erreur(s) · '+r.streak+'/2 bonnes réponses consécutives</span></div>'}).join(''):'<p class="note">Aucune erreur à revoir pour ce niveau. Commence une série pour repérer les décisions à travailler.</p>';
 $('practiceChoices').innerHTML='';$('practiceCorrection').hidden=true;for(const id of ['practiceReveal','practiceNext','practiceOpenRange'])$(id).hidden=true;
 if(!s){$('practiceProgress').textContent='Prêt pour une série';$('practiceQuestion').innerHTML='<h2>Choisis tes situations, puis lance la série.</h2><p class="muted">Commence par l’action immédiate. Le niveau « plan complet » demande aussi de mémoriser la suite indiquée dans le tableau.</p>';return}
 if(finished){const count=s.answers.filter(v=>v!==null).length,correct=s.answers.filter(v=>v===true).length,skipped=s.answers.filter(v=>v===null).length;$('practiceProgress').textContent='Série terminée';$('practiceQuestion').innerHTML='<h2>Série terminée</h2><p class="practice-session">'+correct+' / '+count+'</p><p>'+correct+' réponse(s) conforme(s) au PDF sur '+count+' réponse(s) donnée(s). '+skipped+' correction(s) consultée(s) sans réponse.</p><p class="note">Les erreurs sont disponibles dans « Mes erreurs à revoir ». Tu peux lancer une nouvelle série depuis les réglages.</p>';return}
 const q=s.items[s.index],c=Practice.context(q.page);$('practiceProgress').textContent='Question '+(s.index+1)+' / '+s.items.length;
 $('practiceQuestion').innerHTML='<span class="pill">'+(c.players===3?'3 joueurs':'Heads-up')+' · '+pos(c.hero,c.players)+' · '+c.depth+' BB</span><p class="practice-hand">'+q.hand+'</p><p><strong>'+esc(c.sequence)+'</strong></p><p class="muted">'+(q.level==='action'?'Quelle action immédiate indique le tableau ?':'Quel plan complet indique le tableau ?')+'</p>';
 const options=Practice.choices(q);$('practiceChoices').innerHTML=options.map((label,i)=>'<button data-practice-answer="'+i+'" class="'+(s.revealed&&label===q.answer?'correct':s.revealed&&label===s.chosen?'incorrect':'')+'" '+(s.revealed?'disabled':'')+'>'+esc(label)+'</button>').join('');
 $('practiceReveal').hidden=s.revealed;$('practiceNext').hidden=!s.revealed;$('practiceOpenRange').hidden=!s.revealed;$('practiceNext').textContent=s.index===s.items.length-1?'Voir le bilan':'Question suivante';
 if(s.revealed){const correct=s.chosen===q.answer;$('practiceCorrection').hidden=false;$('practiceCorrection').className='practice-correction'+(s.chosen!==null&&!correct?' wrong':'');$('practiceCorrection').innerHTML='<strong>'+(s.chosen===null?'Correction consultée · non comptabilisée':correct?'Conforme au tableau':'À revoir')+'</strong><p class="gap-top">Réponse : <b>'+esc(q.answer)+'</b></p><p>Plan complet du PDF : <b>'+esc(q.plan)+'</b>.</p><p class="note">Source : Ranges_Expresso_KillTilt.pdf, page '+q.page+'. Les plans après « / » sont repris sans ajouter de taille de relance ou de réponse non précisée. Aucune perte d’EV n’est calculée.</p>'}
}
$('trainThisRange').onclick=()=>{practiceScope='current';practiceSession=null;mode='practice';render()};
$('practiceStart').onclick=startPractice;
$('practiceLevel').onchange=()=>{practiceLevel=$('practiceLevel').value;practiceSession=null;render()};
$('practiceScope').onchange=()=>{practiceScope=$('practiceScope').value;practiceSession=null;render()};
$('practiceReview').onclick=()=>{practiceScope='errors';practiceSession=null;startPractice()};
$('practiceChoices').addEventListener('click',e=>{const b=e.target.closest('[data-practice-answer]');if(b&&practiceSession){const q=practiceSession.items[practiceSession.index];answerPractice(Practice.choices(q)[Number(b.dataset.practiceAnswer)])}});
$('practiceReveal').onclick=()=>answerPractice(null);$('practiceNext').onclick=nextPractice;
$('practiceOpenRange').onclick=()=>{const s=practiceSession;if(!s||!s.revealed)return;const q=s.items[s.index],c=Practice.context(q.page);refState={players:c.players,hero:c.hero,scenario:c.scenario,depth:c.depth,hand:q.hand};mode='reference';render()};
$('jsonQuiz').onclick=()=>{setMode('quiz');if(!quiz)newQuiz()};
const SOLVER_EXAMPLE=/* @SOLVER_EXAMPLE@ */;
/* @SOLVER_UI@ */

solverLoadSettings({config:{players:3,stacks:{BTN:10,SB:10,BB:10}},model:"extended",openSize:2,iterations:100000,seed:20260908});
syncForm();mode="solver";render();if(typeof DecompressionStream!=="undefined")loadSolverExample();
