/* Browser bridge and result viewer for the local worker solver. */
const SolverIO=(()=>{
  const E=createPreflopSolver(Poker);
  function validate(raw){
    if(!raw||raw.version!==1||raw.engine!=='Expresso Lab CFR v1')throw Error('Format de calcul inconnu.');
    const options=E.validateOptions(raw.options),tree=E.build(options);
    if(raw.trained!==options.iterations||raw.evaluated!==options.evaluationDeals||!Array.isArray(raw.nodes)||raw.nodes.length!==tree.decisions.length)throw Error('Calcul incomplet ou arbre incohérent.');
    let seen=new Set();const nodes=raw.nodes.map(n=>{const expected=tree.nodes[n.id];if(!expected||expected.terminal||seen.has(n.id)||n.position!==expected.position||JSON.stringify(n.history)!==JSON.stringify(expected.history))throw Error('Historique de calcul invalide.');seen.add(n.id);if(!n.hands||typeof n.hands!=='object'||Array.isArray(n.hands))throw Error('Mains manquantes.');const hands={};for(const [h,row] of Object.entries(n.hands)){if(Poker.hand(h)!==h||!Array.isArray(row.actions)||row.actions.length!==expected.actions.length)throw Error('Main de calcul invalide.');let total=0;const actions=row.actions.map((a,i)=>{if(Poker.actionKey(a)!==Poker.actionKey(expected.actions[i])||!Number.isFinite(a.frequency)||a.frequency<0||a.frequency>1)throw Error('Stratégie invalide.');total+=a.frequency;let v={type:a.type,...(a.to!==undefined?{to:a.to}:{}),frequency:a.frequency};if(a.ev!==undefined){if(!Number.isFinite(a.ev)||!Number.isFinite(a.ci95)||a.ci95<0)throw Error('EV invalide.');v.ev=a.ev;v.ci95=a.ci95}return v});if(!Poker.near(total,1))throw Error('Les fréquences ne totalisent pas 100 %.');for(const k of ['trainingDeals','strategyEss','evaluationEss'])if(!Number.isFinite(row[k])||row[k]<0)throw Error('Diagnostic de calcul invalide.');if(row.evaluationEss<30&&actions.some(a=>a.ev!==undefined))throw Error('EV insuffisamment échantillonnée.');hands[h]={actions,trainingDeals:row.trainingDeals,strategyEss:row.strategyEss,evaluationEss:row.evaluationEss}}return {id:n.id,position:n.position,history:expected.history,actions:expected.actions.map(({player,...a})=>a),hands}});
    const changes=Array.isArray(raw.rootChanges)?raw.rootChanges.filter(c=>Number.isFinite(c.meanTotalVariation)&&c.meanTotalVariation>=0&&c.meanTotalVariation<=1&&Number.isInteger(c.iteration)&&c.iteration<=raw.trained):[];
    return {version:1,engine:raw.engine,options,trained:raw.trained,evaluated:raw.evaluated,treeNodes:tree.nodes.length,decisionNodes:nodes.length,rootChanges:changes,nodes,elapsedMs:Number.isFinite(raw.elapsedMs)&&raw.elapsedMs>=0?raw.elapsedMs:0};
  }
  function pack(result){return RangeData.validate({schemaVersion:1,name:'CFR calculé · '+result.options.config.players+' joueurs · '+Object.values(result.options.config.stacks).join('/')+' BB',provenance:{kind:'computed',title:'Expresso Lab CFR v1 · modèle préflop simplifié',reference:'Calcul reproductible : graine '+result.options.seed+', '+result.trained+' distributions d’apprentissage, '+result.evaluated+' distributions indépendantes d’évaluation.',assumptions:'Chip EV, sans ante ni prélèvement par pot. Stratégies moyennes calculées par CFR avec échantillonnage des cartes. Aucun certificat d’équilibre ou d’exploitabilité ; pas de garantie de convergence vers Nash à 3 joueurs. Taille d’ouverture '+result.options.openSize+' BB. '+(result.options.model==='pushfold'?'Actions limitées au push/fold.':'Deux relances non all-in maximum, 3-bets au minimum légal ou à 3 fois la mise, all-in permis ensuite.')+' EV nettes depuis le début de la main, blindes incluses. Les EV sont masquées si le nombre effectif d’échantillons est inférieur à 30.',postflop:result.options.model==='pushfold'?'Aucune décision postflop : push/fold.':'Flop, turn et river distribués puis abattage sans aucune mise postflop. Cette hypothèse peut fortement fausser les limps et les calls. Ce modèle n’est pas le Hold’em complet.',evUnit:'BB nettes depuis le début de la main (blindes incluses)'},spots:result.nodes.map(node=>({label:node.position+' · '+solverHistory(node.history),config:{...result.options.config,hero:node.position},history:node.history,hands:Object.fromEntries(Object.entries(node.hands).map(([h,row])=>[h,{actions:row.actions.map(({ci95,...a})=>a),explanation:'Calcul du modèle simplifié. Échantillons utiles de stratégie : '+Math.round(row.strategyEss)+' ; évaluation : '+Math.round(row.evaluationEss)+'. Les fréquences sont approximatives et l’équilibre n’est pas certifié.'}]))}))})}
  return {validate,pack};
})();
let solverResult=null,solverBusy=false,solverWorker=null,solverWorkerURL=null,solverProgress=null,solverNodeId=null,solverHand='AKo',solverOrigin='';
function solverHistory(history){return history.length?history.map(a=>a.player+' '+({raise:'raise',allin:'all-in',call:'call',limp:'limp',fold:'fold',check:'check'}[a.type])+(a.to!==undefined?' '+fmt(a.to):'')).join(' → '):'Pot non ouvert'}
function solverInput(){const n=Number($('solverFormat').value),stacks={};for(const p of Poker.positions(n))stacks[p]=Number($('solverStack'+p).value);return {config:{players:n,hero:n===3?'BTN':'SB',stacks,sb:.5,ante:0,anteMode:'each',objective:'chipEV',payouts:n===3?[1,0,0]:[1,0],rake:0},model:$('solverModel').value,openSize:Number($('solverOpenSize').value),iterations:Number($('solverEffort').value),evaluationDeals:Math.floor(Number($('solverEffort').value)/2),seed:Number($('solverSeed').value)}}
function solverSignature(o){return JSON.stringify({config:Poker.config(o.config),model:o.model,openSize:o.openSize})}
function solverLoadSettings(o){$('solverFormat').value=o.config.players;for(const p of Poker.positions(o.config.players))$('solverStack'+p).value=o.config.stacks[p];$('solverModel').value=o.model;$('solverOpenSize').value=o.openSize;$('solverEffort').value=[20000,100000,500000].includes(o.iterations)?o.iterations:100000;$('solverSeed').value=o.seed;solverSyncPositions();}
function solverSyncPositions(){const n=Number($('solverFormat').value),hero=$('solverHero').value;$('solverBTNField').hidden=n===2;$('solverHero').innerHTML=Poker.positions(n).map(p=>'<option value="'+p+'">'+pos(p,n)+'</option>').join('');$('solverHero').value=Poker.positions(n).includes(hero)?hero:'SB';}
function solverSettingsChanged(){solverSyncPositions();error('solverError','');render()}
function solverShift(delta,p=null){if(solverBusy)return;const ps=p?[p]:Poker.positions(Number($('solverFormat').value)),values=ps.map(p=>Number($('solverStack'+p).value));if(values.some(v=>!Number.isFinite(v)||v<1||v>25))return;const shift=Math.max(1-Math.min(...values),Math.min(25-Math.max(...values),delta));ps.forEach((p,i)=>$('solverStack'+p).value=Poker.round(values[i]+shift));solverSettingsChanged()}
function solverFinishWorker(){if(solverWorker)solverWorker.terminate();if(solverWorkerURL)URL.revokeObjectURL(solverWorkerURL);solverWorker=null;solverWorkerURL=null;solverBusy=false;}
function solverStart(){if(solverBusy)return;let options;try{options=createPreflopSolver(Poker).validateOptions(solverInput());if(typeof Worker==='undefined')throw Error('Ce navigateur ne permet pas les calculs en arrière-plan. Ouvrez le HTML dans Chrome, Edge ou Firefox.')}catch(e){error('solverError',e.message);return}
 error('solverError','');solverBusy=true;solverProgress={phase:'build',done:0,total:options.iterations};
 const workerCode=$('poker-core').textContent+'\n'+$('poker-solver-engine').textContent+'\nself.onmessage=async(e)=>{try{const result=await createPreflopSolver(Poker).run(e.data,p=>self.postMessage({kind:"progress",progress:p}));self.postMessage({kind:"result",result})}catch(error){self.postMessage({kind:"error",message:error.message})}};';
 try{solverWorkerURL=URL.createObjectURL(new Blob([workerCode],{type:'text/javascript'}));solverWorker=new Worker(solverWorkerURL);solverWorker.onmessage=e=>{if(e.data.kind==='progress'){solverProgress=e.data.progress;if(mode==='solver')renderSolverProgress()}else if(e.data.kind==='result'){try{solverResult=SolverIO.validate(e.data.result);solverOrigin='Calcul effectué dans ce navigateur';solverNodeId=null;solverFinishWorker();render()}catch(err){solverFinishWorker();error('solverError',err.message);render()}}else if(e.data.kind==='error'){solverFinishWorker();error('solverError',e.data.message);render()}};solverWorker.onerror=e=>{solverFinishWorker();error('solverError','Le calcul a échoué : '+(e.message||'worker indisponible')+'. Le dernier résultat terminé est conservé.');render()};solverWorker.postMessage(options);render()}catch(e){solverFinishWorker();error('solverError',e.message);render()}
}
function renderSolverProgress(){const p=solverProgress||{phase:'build',done:0,total:1},ratio=p.done/p.total;$('solverProgressBar').value=p.phase==='evaluate'?80+ratio*20:p.phase==='train'?ratio*80:0;$('solverProgressText').textContent=(p.phase==='build'?'Construction de l’arbre':p.phase==='train'?'Apprentissage des stratégies':'Évaluation indépendante des EV')+' · '+fmt(p.done)+' / '+fmt(p.total);}
function renderSolver(){
 $('solverView').hidden=false;for(const id of ['referenceView','practiceView','workspace','library','quizBar','dataBanner'])$(id).hidden=true;for(const id of ['navSolver','navReference','navAnalyze','navQuiz','navLibrary']){$(id).classList.toggle('active',id==='navSolver');$(id).setAttribute('aria-pressed',id==='navSolver')}
 $('solverRun').disabled=solverBusy;$('solverStop').hidden=!solverBusy;$('solverProgressBox').hidden=!solverBusy;
 for(const id of ['solverFormat','solverStackBTN','solverStackSB','solverStackBB','solverModel','solverOpenSize','solverEffort','solverSeed','solverDepthLess','solverDepthMore','solverImport','solverExample'])$(id).disabled=solverBusy;
 $('solverModelNote').textContent=$('solverModel').value==='pushfold'?'Modèle restreint : tapis ou fold. Aucune stratégie de limp ou de petite relance.':'Modèle simplifié : après le préflop, tout le monde checke jusqu’à l’abattage. Les limps et calls peuvent être fortement biaisés.';
 if(solverBusy)renderSolverProgress();let matched=false;try{matched=!!solverResult&&solverSignature(solverInput())===solverSignature(solverResult.options)}catch{}
 const usable=matched&&!solverBusy;$('solverOutputs').hidden=!usable;$('solverEmpty').hidden=usable;$('solverExport').disabled=!usable;$('solverSendToAnalysis').disabled=!usable;
 $('solverEmpty').textContent=solverBusy?'Calcul en cours. Vous pouvez changer d’onglet ou arrêter le calcul.':solverResult?'Les paramètres ont changé. Cliquez sur « Calculer les ranges » pour obtenir les stratégies de cette configuration.':'Choisissez les tapis puis lancez le calcul. Le moteur explore toutes les branches du modèle pour cette configuration.';
 if(!usable)return;
 const result=solverResult,n=result.options.config.players,hero=$('solverHero').value,available=result.nodes.filter(v=>v.position===hero).sort((a,b)=>a.history.length-b.history.length||a.id-b.id);
 let node=available.find(v=>v.id===Number(solverNodeId));if(!node)node=available.find(v=>v.history.length===1&&v.history[0].player==='BTN'&&v.history[0].type==='raise')||available[0];solverNodeId=node?.id??null;
 $('solverSpot').innerHTML=available.map(v=>'<option value="'+v.id+'">'+esc(solverHistory(v.history))+'</option>').join('');if(node)$('solverSpot').value=node.id;
 const last=result.rootChanges.at(-1);$('solverSummary').textContent=solverOrigin+' · '+fmt(result.trained)+' distributions d’apprentissage + '+fmt(result.evaluated)+' d’évaluation · '+result.decisionNodes+' situations calculées · '+(result.options.model==='pushfold'?'push/fold':'préflop avec abattage sans mises postflop')+'.';
 $('solverDiagnostics').textContent='Variation moyenne de la stratégie de départ entre les deux derniers points de contrôle : '+(last?pct(last.meanTotalVariation):'non disponible')+'. Ce diagnostic ne mesure pas l’exploitabilité et ne certifie pas un équilibre. À 3 joueurs, cette méthode n’offre pas de garantie de convergence vers Nash.';
 if(!node){$('solverMatrix').innerHTML='';$('solverDecision').innerHTML='<p>Aucune décision à prendre pour cette position dans cet arbre.</p>';$('solverCoverage').textContent='Aucune décision';return}
 $('solverHand').value=solverHand;$('solverCoverage').textContent=Object.keys(node.hands).length+' / 169 mains observées';
 $('solverMatrix').innerHTML=Poker.allHands().map(h=>{const row=node.hands[h];let bg='',tip='Non apprise dans ce calcul';if(row){let stop=0;bg='background:linear-gradient(90deg,'+row.actions.filter(a=>a.frequency>0).map(a=>{const start=stop;stop+=a.frequency*100;return colors[a.type]+' '+start+'% '+stop+'%'}).join(',')+')';tip=row.actions.map(a=>labels[a.type]+(a.to===undefined?'':' '+fmt(a.to))+' '+pct(a.frequency)).join(' / ')+(row.strategyEss<30?' · Faible support statistique':'')}
 return '<button class="cell '+(row?'known ':'')+(row?.actions.every(a=>!a.frequency||a.type==='fold')?'fold-only ':'')+(h===solverHand?'selected':'')+'" data-solver-hand="'+h+'" style="'+bg+'" aria-label="'+esc(h+' : '+tip)+'" aria-pressed="'+(h===solverHand)+'" title="'+esc(tip)+'">'+h+'</button>'}).join('');
 const row=node.hands[solverHand];if(!row){$('solverDecision').innerHTML='<h2>Main insuffisamment apprise</h2><p>Augmentez le nombre de simulations pour cette branche.</p>';return}
 const s=Poker.replay(result.options.config,node.history),best=[...row.actions].sort((a,b)=>b.frequency-a.frequency)[0];
 $('solverDecision').innerHTML='<div class="eyebrow">'+esc(solverHand)+' · '+pos(hero,n)+'</div><h2 class="result-title">'+esc(actionText(best,s))+'</h2><p class="note">Action la plus fréquente dans la stratégie moyenne calculée : '+pct(best.frequency)+'.</p>'+ (best.to!==undefined?'<p>'+fmt(best.to)+' BB au total · '+fmt(best.to-s.seats[hero].paid)+' BB à ajouter.</p>':'')+'<div class="solver-table-scroll"><table class="distribution"><thead><tr><th>Action · total BB</th><th>Fréquence</th><th>EV · BB</th><th>± incertitude</th></tr></thead><tbody>'+row.actions.map(a=>'<tr><td>'+esc(actionText(a,s))+'</td><td>'+pct(a.frequency)+'</td><td>'+(a.ev===undefined?'—':fmt(a.ev))+'</td><td>'+(a.ci95===undefined?'—':fmt(a.ci95))+'</td></tr>').join('')+'</tbody></table></div><p class="note">EV nettes depuis le début de la main, blindes incluses : un fold en SB vaut −0,5 BB. L’intervalle affiché est une approximation à 95 % de l’incertitude de simulation ; il ne couvre ni l’erreur du modèle ni une absence de convergence.</p><p class="note">Échantillons utiles : stratégie '+fmt(row.strategyEss)+' · évaluation '+fmt(row.evaluationEss)+'. Les EV sont masquées en dessous de 30 échantillons utiles.</p>'+(row.strategyEss<30?'<p class="banner">Cette main dispose de peu d’observations utiles dans cette branche. Les fréquences sont fragiles.</p>':'');
}
async function loadSolverExample(){if(solverBusy)return;try{if(typeof DecompressionStream==='undefined')throw Error('Chargement de l’exemple indisponible dans ce navigateur. Vous pouvez lancer un nouveau calcul.');const binary=atob(SOLVER_EXAMPLE),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0)),text=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate'))).text();solverResult=SolverIO.validate(JSON.parse(text));solverLoadSettings(solverResult.options);solverNodeId=null;solverOrigin='Calcul intégré reproductible · graine '+solverResult.options.seed;error('solverError','');render()}catch(e){error('solverError',e.message);render()}}
$('navSolver').onclick=()=>{mode='solver';render()};$('solverRun').onclick=solverStart;$('solverStop').onclick=()=>{solverFinishWorker();error('solverError','Calcul arrêté. Aucun résultat partiel n’a été publié.');render()};
for(const id of ['solverFormat','solverStackBTN','solverStackSB','solverStackBB','solverModel','solverOpenSize'])$(id).addEventListener('change',solverSettingsChanged);
$('solverHero').onchange=()=>{solverNodeId=null;render()};$('solverSpot').onchange=()=>{solverNodeId=Number($('solverSpot').value);render()};$('solverHand').onchange=()=>{try{solverHand=Poker.hand($('solverHand').value);error('solverError','');render()}catch(e){error('solverError',e.message)}};
$('solverMatrix').addEventListener('click',e=>{const b=e.target.closest('[data-solver-hand]');if(b){solverHand=b.dataset.solverHand;render()}});
$('solverDepthLess').onclick=()=>solverShift(-1);$('solverDepthMore').onclick=()=>solverShift(1);
for(const p of ['BTN','SB','BB'])$('solverStack'+p).addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey||!e.deltaY||Math.abs(e.deltaX||0)>Math.abs(e.deltaY))return;e.preventDefault();solverShift(e.deltaY<0?1:-1,p)},{passive:false});
$('solverExport').onclick=()=>{if(solverResult)download('ranges-calculees-expresso.json',solverResult)};
$('solverSendToAnalysis').onclick=()=>{try{if(!solverResult)return;acceptPack(SolverIO.pack(solverResult));const index=solverResult.nodes.findIndex(v=>v.id===solverNodeId);openSpot(Math.max(0,index),solverHand);mode='analyze';render();toast('Stratégies calculées chargées dans l’analyse avancée.')}catch(e){error('solverError',e.message)}};
$('solverImport').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>30000000)throw Error('Fichier de calcul trop volumineux (maximum 30 Mo).');const r=SolverIO.validate(JSON.parse(await file.text()));solverResult=r;solverLoadSettings(r.options);solverNodeId=null;solverOrigin='Calcul importé · provenance non auditée';error('solverError','');render()}catch(e){error('solverError',e.message)}finally{$('solverImport').value=''}};
$('solverExample').onclick=loadSolverExample;
solverSyncPositions();
